### PR TITLE
feat(Icons): add/update/correct Icons

### PR DESCRIPTION
**Pull request by CITguy**
* **Stop tracking `*.sketch` files in git**
  * Kactus can regenerate these files from the JSON metadata at any time).
* Rename nested color symbols to `Icon Color` for better UX in override panel
* Remove Icon Slices
* Replace `billing` icon
* Replace `server` icon
* Replace `technical-change` icon
* Replace `technical-incident` icon
* Replace `ticketing` icon
* Renamed `server` to `server/plain`
* Renamed `technical-change` to `server/config`
* Renamed `technical-incident` to `server/incident`
* Renamed `input/url` to `globe`
* Correct `angle/*` geometry
* Correct `calendar` geometry
* Correct `exclamation/circle` geometry
* Correct `exclamation/triangle` geometry
* Correct `external-link` geometry
* Correct `globe` geometry
* Correct `minus/plain` geometry
* Correct `padlock/locked` geometry
* Correct `payment` geometry and alignment
* Correct `plus-or-minus` geometry
* Correct `trash` geometry
* Add `angle/bottom`
* Add `angle/end`
* Add `angle/start`
* Add `angle/top`
* Add `exclamation/triangle`
* Add `file`
* Add `flag`
* Add `key`
* Add `mime/archive`
* Add `mime/audio`
* Add `mime/code`
* Add `mime/data`
* Add `mime/image`
* Add `mime/system`
* Add `mime/text`
* Add `mime/video`
* Add `paperclip`

### CODE REVIEW

**Comment by technabors** [comment]
@CITguy @araiford  Still trying to figure out what to do with these conflicting files. Check my logic here. I believe I can pull this branch down locally and run `git rebase`. I can clear up the merge conflict with `helix-ui-components/Icons-Symbols/BAD33C5D-A585-4457-B725-1B164F85D9C7/symbolMaster.json` and then do the following to accept the updated sketch files (which I can't resolve because it isn't a flat file.`

1. `git checkout --theirs -- helix-redline-specs.sketch`
2. `git checkout --theirs -- helix-ui-components.sketch`
3. commit these changes
4. push up and merge.

Thoughts?

**Comment by CITguy** [comment]
I have a feeling that running 1 and 2 may trample on work done in the PR. Is there any way we can keep the `*.sketch` files out of version control for the dev branches, and create a process to save them in a different branch?

**Comment by technabors** [comment]
We can keep them out but them users won't be able to download the assets, which might not be a problem. As for the creation process I tried taking the folder structure and performing the following to no avail.

```
zip -r helix-ui-components/  helix-ui-components.zip
mv helix-ui-components.zip helix-ui-components.sketch
```

I tried this because the reverse process works on a regular sketch file and provides a nested folder. But it appears Kactus might be doing something additional to file structure.

**Comment by CITguy** [comment]
@araiford, @technabors 

Based on what was discovered with git + Kactus integration, the `*.sketch` binaries were removed from version control. Kactus can generate these files from the tracked JSON metadata, so there's no need to track the binaries.

Neither `git checkout --theirs` nor `git checkout --ours` is optimal as it is likely to clobber updates on one side or the other.

**Pull request merged**
